apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sniff
spec:
  selector:
    matchLabels:
      app: sniff
  serviceName: "sniff"
  replicas: 1
  template:
    metadata:
      labels:
        app: sniff
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 2
      containers:
      - name: ziply
        image: wknickless/netsniff-ng:latest
        command:
          - netsniff-ng
          - --in
          - ziply
          - --out
          - /ziply/
          - --prefix
          - ziply-
          - --silent
          - --interval
          - 1hrs
        volumeMounts:
        - name: ziply-packets
          mountPath: /ziply
        securityContext:
          privileged: true
      - name: cradlepoint
        image: wknickless/netsniff-ng:latest
        command:
          - netsniff-ng
          - --in
          - cradlepoint
          - --out
          - /cradlepoint/
          - --prefix
          - cradlepoint-
          - --silent
          - --interval
          - 1hrs
        volumeMounts:
        - name: cradlepoint-packets
          mountPath: /cradlepoint
        securityContext:
          privileged: true
      - name: speedify
        image: wknickless/netsniff-ng:latest
        command:
          - netsniff-ng
          - --in
          - enp1s0f3
          - --out
          - /speedify/
          - --prefix
          - speedify-
          - --silent
          - --interval
          - 1hrs
        volumeMounts:
        - name: speedify-packets
          mountPath: /speedify
        securityContext:
          privileged: true
      volumes:
      - name: ziply-packets
        hostPath:
          path: /mnt/disk/purple/ziply
          type: DirectoryOrCreate
      - name: cradlepoint-packets
        hostPath:
          path: /mnt/disk/purple/cradlepoint
          type: DirectoryOrCreate
      - name: speedify-packets
        hostPath:
          path: /mnt/disk/purple/speedify
          type: DirectoryOrCreate

