network:
  version: 2
  renderer: networkd
  bridges:
    milkyway:
      interfaces:
        - enp1s0f0
        - enp1s0f1
      link-local: [ ]
      dhcp4: no
      dhcp6: no
  ethernets:
    enp1s0f0:
      link-local: [ ]
      dhcp4: no
      dhcp6: no
    enp1s0f1:
      link-local: [ ]
      dhcp4: no
      dhcp6: no
